### ISSUE TITLE
removes 'auto' from 'margin: 0 auto'

### ISSUE THREAD

**Issue by jekrb** [ben-eb/postcss-merge-rules#11]
Greetings!  Thanks for the awesome plugin!

It seems that `margin: 0 auto` becomes `margin: 0`.  I believe this may be bug.

**Comment by ben-eb** [comment]
I think it might be a problem with your environment, because I can't reproduce this. Can you share some more details?

**Comment by jekrb** [comment]
Sure, thanks!
I was using `postcss-import', `autoprefixer`, and `postcss-merge-rules`. Then I used `uncss` on the postcss output to remove unused css.  Finally I used `cssnano` on the `uncss` output to minify the css.
I'm using the postcss js api.

It looked something like this:

```

postcss([atImport, autoprefixer, mergeRules])
  .process(css, {
    from: 'src/styles/index.css'
  })
  .then(result => {
    fs.writeFileSync('public/styles/bundle.css', result.css)
    const opts = {
      stylesheets: ['styles/bundle.css'],
      csspath: '../public'
    }
    uncss(htmls, opts, (err, output) => {
      if (err) console.error(err)
      fs.writeFileSync('public/styles/bundle.css', output)
      postcss([cssnano])
        .process(output)
        .then(result => {
          fs.writeFileSync('public/styles/bundle.css', result.css)
        })
    })
  })
```

This is my first attempt at using postcss and it's various plugins, I have been really off with something!

**Comment by ben-eb** [comment]
* postcss-merge-rules is already bundled with cssnano, does it need to be ran twice?
* Do you mean that you are using https://github.com/postcss/postcss-js ?

**Comment by jekrb** [comment]
Oh did

**Comment by jekrb** [comment]
Didn't re

**Comment by jekrb** [comment]
Didn't realize that cssnano has postcss merge rules built in! 

And no I meant postcss js api as the docs called it:  https://github.com/postcss/postcss/blob/master/README.md#js-api

**Comment by ben-eb** [comment]
Can you reproduce this with just cssnano?

**Comment by jekrb** [comment]
I can't seem to reproduce it.  But thanks for the heads up about rule merging already being in cssnano.  Sorry about the hassle!

**Comment by ben-eb** [comment]
No worries.
