### ISSUE TITLE
Doesn't want to work in WebPack

### ISSUE THREAD

**Issue by IngwiePhoenix** [ben-eb/postcss-merge-rules#4]
I am using the postcss loader for WebPack and tried to run this plugin. This is what I get:

```
    ERROR in ./~/css-loader!./~/postcss-loader?keepSpecialComments=0&processImport=true&rebase=true&relativeTo=/Users/Ingwie/Work/BIRD3&shorthandCompacting=true&target=/Users/Ingwie/Work/BIRD3/cdn/app&sourceMap!./themes/dragonsinn/css/bs-extra.css
    Module build failed: TypeError: Cannot read property 'map' of undefined
        at getDeclarations (/Users/Ingwie/Work/BIRD3/node_modules/postcss-merge-rules/index.js:55:22)
        at partialMerge (/Users/Ingwie/Work/BIRD3/node_modules/postcss-merge-rules/index.js:77:67)
        at /Users/Ingwie/Work/BIRD3/node_modules/postcss-merge-rules/index.js:155:17
        at /Users/Ingwie/Work/BIRD3/node_modules/postcss-loader/node_modules/postcss/lib/container.js:141:30
        at /Users/Ingwie/Work/BIRD3/node_modules/postcss-loader/node_modules/postcss/lib/container.js:102:26
        at Root.each (/Users/Ingwie/Work/BIRD3/node_modules/postcss-loader/node_modules/postcss/lib/container.js:89:22)
        at Root.eachInside (/Users/Ingwie/Work/BIRD3/node_modules/postcss-loader/node_modules/postcss/lib/container.js:101:21)
        at Root.eachRule (/Users/Ingwie/Work/BIRD3/node_modules/postcss-loader/node_modules/postcss/lib/container.js:139:21)
        at /Users/Ingwie/Work/BIRD3/node_modules/postcss-merge-rules/index.js:161:13
        at LazyResult.run (/Users/Ingwie/Work/BIRD3/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:193:24)
```

Disabling sourcemaps entirely doesn't do a thing either.

**Comment by ben-eb** [comment]
I think it's related to this: https://github.com/ben-eb/postcss-merge-rules/issues/2

I need some way to be able to replicate this because it might be a hole in the AST (and therefore a problem in PostCSS core, affecting more than just this plugin).

**Comment by IngwiePhoenix** [comment]
This is the only PostCSS plugin I use. So I thought it should work out. the CSS file pointed out in my repost above is also a very tiny one and all it does is enhancing some Bootstrap things.

How can I verify that the AST is broken or not?

**Comment by ben-eb** [comment]
The AST is broken if the rule node doesn't have a `nodes` property that is an array type (or it is non-existent). The fix could be as simple as checking that the `nodes` property exists, *but* that is adding additional logic to the plugin where PostCSS should be providing us an empty array. I don't think it is right to start distrusting the AST in this way.

I'd be grateful if you could throw this together in a repo so that I can reproduce.

**Comment by IngwiePhoenix** [comment]
https://github.com/DragonsInn/BIRD3/tree/postcss-integration-webpack

You need to install `postcss-merge-rules` since it is not annotated in the dependency list, yet. I made this branch for demonstration :).

To set up:

```
$ bower install
$ npm install
```

You don't need the composer modules, they are soley used for the PHP backend based on Yii. However, you'll need to pull the submodules. So, you'll likely want to clone it like this:

    $ git clone -b postcss-integration-webpack --recursive https://github.com/DragonsInn/BIRD3.git

To run WebPack: `npm run compile`.

It's a pretty big project, I know. Sorry for the load! x) But it is the exact environment that I use. The branch is set up to break with the very errors I have shown above.

**Comment by IngwiePhoenix** [comment]
I just realized I had forotten to mention the one or other thing, and the INI example was outdated too. I put details into the README file. They should help.

Sorry again for this being such gigantic codebase. I thought that this was the best way to reproduce my environment rather than trying to cram together something that likely would actually work instead of break. :)

**Comment by ben-eb** [comment]
Thanks for that, I managed to track down the bug. The behaviour only affects standalone usage of this module, because when using [cssnano](https://github.com/ben-eb/cssnano) all comments are stripped out beforehand. The module was trying to get the `nodes` property of a comment node which doesn't exist. Now it will skip comment nodes.

**Comment by IngwiePhoenix** [comment]
Awesome! Ill try this one out on my end. :)

**Comment by IngwiePhoenix** [comment]
Works as expected. Thanks!

**Comment by ben-eb** [comment]
Awesome. Thanks again for sharing your code. :+1:

**Comment by IngwiePhoenix** [comment]
Very welcome! I had planned to open-source the project EXACTLY for this kinda case. No need to be all "i cant share" :). Makes code-fixing way easier. Thanks for your help and have a great coding! ^^
