### ISSUE TITLE
Update caniuse

### ISSUE THREAD

**Issue by kristoferjoseph** [ben-eb/postcss-merge-rules#46]
see ben-eb/cssnano#340

**Comment by ben-eb** [comment]
I'm pretty sure that this has been resolved in the latest browserslist, so am going to close this issue.

https://github.com/ben-eb/cssnano/issues/340#issuecomment-274201839

**Comment by notacouch** [comment]
I am not sure what the issue was, if it's related to caniuse-db or what, but it popped up for me, see comment: https://github.com/ben-eb/cssnano/issues/340#issuecomment-283525292
