### ISSUE TITLE
caniuse database adds a lot of weight to this package

### ISSUE THREAD

**Issue by segphault** [ben-eb/postcss-merge-rules#49]
The caniuse-api package brings in the entire caniuse database, which is 8MB on disk. Is it possible to avoid that? It seems like you only need to be able to check CSS selectors, which would probably be a much more manageable subset of the total database.

**Comment by ben-eb** [comment]
I'm working on a stripped-down version of this dataset, but ironically if I were to load a subset of this data right now and you were to use this module alongside a caniuse-db consumer (such as autoprefixer) you'd get even more to download. So I strongly believe that we need a unified solution.

The project needs work still but it's available here: https://github.com/ben-eb/caniuse-lite

**Comment by ben-eb** [comment]
Resolved in https://github.com/ben-eb/cssnano/releases/tag/v4.0.0-rc.0.
