### ISSUE TITLE
Support `browserslist` `2` version

### ISSUE THREAD

**Issue by evilebottnawi** [ben-eb/postcss-merge-rules#51]
Maybe just use `"browserslist": "^1.5.2 || ^2.0.0"` :+1:

**Comment by ben-eb** [comment]
It's coming with cssnano 4, currently blocked by https://github.com/Nyalab/caniuse-api/pull/59.

**Comment by ben-eb** [comment]
Resolved in https://github.com/ben-eb/cssnano/releases/tag/v4.0.0-rc.0.
