### ISSUE TITLE
Upgrade caniuse-api dependency to v2.0.0

### ISSUE THREAD

**Issue by fr0** [ben-eb/postcss-merge-rules#53]
Version 2.0.0 of `caniuse-api` relies on `caniuse-lite` instead of `caniuse-db`, which saves 6.5 MB of disk space in the `node_modules` folder.

**Comment by ben-eb** [comment]
I know, I wrote that patch (and maintain caniuse-lite). 😄 

The current release candidate of cssnano (and by extension, postcss-merge-rules) already use it! We have to wait a little longer until 4.0 goes live "for real" but you can check it out by `npm i cssnano@next`. 👍 

https://github.com/ben-eb/cssnano/releases/tag/v4.0.0-rc.0

**Comment by fr0** [comment]
Thank you!
