### ISSUE TITLE
Update postcss dependency version

### ISSUE THREAD

**Issue by klapec** [ben-eb/postcss-merge-rules#8]
This package currently depends on postcss "^4.1.16". Since the latest postcss update (5.0.1), I am getting the following error:
```
Your current PostCSS version is 5.0.1, but postcss-merge-rules uses 4.1.16. Perhaps this is the source of the error below.
[12:33:38] TypeError in plugin 'gulp-postcss'
Message:
    Cannot read property 'before' of undefined
```

**Comment by ai** [comment]
Do you use `postcss-import`? It has some unhookable case with `postcss.parse`.

**Comment by klapec** [comment]
I do, yes. Here's the list of plugins I use:
```
'autoprefixer'
'lost'
'css-mqpacker'
'cssnano'
'postcss-custom-media'
'postcss-import'
'postcss-media-minmax'
'postcss-nested'
'postcss-simple-vars'
'postcss-size'
'postcss-will-change'
```

**Comment by ben-eb** [comment]
PostCSS 5.0 support is planned for cssnano 3. https://github.com/ben-eb/cssnano/issues/46#issuecomment-132757272

As you can appreciate I have a *lot* of modules to update for this, so I plan to stay on `4.x` for the time being. If you would like to use PostCSS 5.0 modules alongside cssnano, then you could use [gulp-cssnano](https://github.com/ben-eb/gulp-cssnano) for the time being.

```js
gulp.task('css', function () {
  return gulp.src('*.css')
    .pipe(postcss([ /* plugins... */ ]))
    .pipe(cssnano())
    .pipe(gulp.dest('out'));
});
```

**Comment by ai** [comment]
Seems like `postcss-import` broke a AST wwith 4.x nodes and `postcss-merge-rules` is only a plugin who get this issue.

**Comment by ai** [comment]
https://github.com/postcss/postcss-import/issues/75

**Comment by ben-eb** [comment]
Fixed since https://github.com/ben-eb/postcss-merge-rules/commit/82b502320b8d976a8113049d012f6277b238ec9b.
